apiVersion: v1
kind: Service
metadata:
  name: bitcoin-exporter
  namespace: wix
spec:
  selector:
    app: bitcoin-exporter
  ports:
    - protocol: TCP
      port: 8000  # External port
      targetPort: 8000  # Port on the container
  type: NodePort

